# Generated by Django 3.2.4 on 2021-06-29 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('date', models.DateField(verbose_name='Date')),
                ('readCnt', models.IntegerField(default=0, verbose_name='TotalRead')),
                ('cmntCnt', models.IntegerField(default=0, verbose_name='TotalComment')),
                ('is_del', models.BooleanField(default=0, verbose_name='isDel')),
            ],
            options={
                'verbose_name': 'BookInfo',
                'verbose_name_plural': 'BookInfo',
                'db_table': 'tb_BookInfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('gender', models.SmallIntegerField(choices=[(0, 'female'), (1, 'male')], default=0, verbose_name='Gender')),
                ('cmnt', models.CharField(max_length=200, null=True, verbose_name='Comment')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.bookinfo', verbose_name='inBook')),
            ],
            options={
                'verbose_name': 'HeroInfo',
                'verbose_name_plural': 'HeroInfo',
                'db_table': 'tb_HeroInfo',
                'managed': True,
            },
        ),
    ]
